#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Formatando o código automaticamente..."
npm run format

echo "✅ Verificando se o código está formatado corretamente..."
npm run format-check

echo "🧪 Executando testes da API Pet Scheduler..."
npm run test

echo "✨ Pré-commit concluído com sucesso!"
